### ISSUE TITLE
Link to Law Foundation website

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz.github.io#10]
The logo in the footer: https://www.lawfoundation.org.nz/

**Comment by airbr** [comment]
https://github.com/openlawnz/openlawnz.github.io/pull/12/commits/22c0a886ccdf7d2ca03cbc8db6bef988adade21a

**Comment by trued-code** [comment]
I have update the pages so a click on the OpenLaw logo opens the OpenLaw web page

**Comment by caionnx** [comment]
Merged https://github.com/openlawnz/openlawnz.github.io/pull/12
