### ISSUE TITLE
Small Improvements

### ISSUE THREAD

**Issue by caionnx** [openlawnz/openlawnz.github.io#14]
General:
- [x] Improve home's image alt text
- [x] Add `mailto` link on `enquires@openlaw.nz` in the footer.

On mobile view:
- [x] Fix Law Foundation logo in the footer because it's overlapping the text `supported by` 
- [x] Change the welcome text to occupy the whole screen. The image can be displayed after the text.
- [x] Fix nav menu items because the text is overtaking the background (360px screen and below)
- [x] Add `overflow-y: scroll` on `id="overview"` in Platform Areas Page so the table is better displayed with the overall layout.

SEO:
- [x] Adapt the pages `title` according to its content.

**Comment by airbr** [comment]
1. [Direction I am going in- using title attr on divs because images are included via CSS]( https://stackoverflow.com/questions/4216035/css-background-image-alt-attribute)

**Comment by caionnx** [comment]
> 
> 
>     1. [Direction I am going in- using title attr on divs because images are included via CSS](https://stackoverflow.com/questions/4216035/css-background-image-alt-attribute)
> 
>     2. Done
> 
>     3. Do you mean on a mobile view?

1. Check the image inside `intro_image` div
3. Exactly

**Comment by airbr** [comment]
@caionnx Just checking, so some of the images are included via CSS i.e 
```
#nav_box{
    background-image: url(images/OpenLaw_Tab_Background.jpg);
    background-size: cover;}
```
The W3Spec seems to be to put descriptive title tags on the elements the images appear on. 
So would it be appropriate to put title attributes on where nav box was placed?

**Comment by caionnx** [comment]
@airbr not that one, the image aside from the text "Your contributions will help those who seek access to justice. For more information, see our main website". The background that you mentioned is ok to not have a text do describe it.
